### ISSUE TITLE
Updated to 45.1.0 : SFDX: Create * no longer works

### ISSUE THREAD

**Issue by ad1969** [forcedotcom/salesforcedx-vscode#1046]
### Summary
It looks like after the Salesforce Extension Pack upgrade to 45.0.1, none of the SFDX create menues work. I no longer see the Command that allows me to enter a name.

### Steps To Reproduce:

1. Right click and select any SFDX: Create menu or Ctrl+Shift+P and select the same menu
2. The prompt to enter the name no longer appears.

### Expected result

A prompt that will allow me to enter the name of the component or apex page.

### Actual result

No prompt, command 'sfdx.force.lightning.component.create' not found error

### Additional information

![image](https://user-images.githubusercontent.com/5445582/52669793-a8baad80-2edc-11e9-8d7f-69c9cec58c94.png)

![image](https://user-images.githubusercontent.com/5445582/52669821-bcfeaa80-2edc-11e9-872e-37e8d02e2f38.png)

**VS Code Version**: 1.31.1

**SFDX CLI Version**: 45.1.0

**OS and version**: Windows 10

**Comment by patmcclellan** [comment]
I had a similar issue for the last few days that was just resolved. In my situation, VSCode stopped seeing that I had a project loaded, and it would only give me the SFDX: Create Project commands (opposite of your situation). See thread for resolution. https://github.com/forcedotcom/salesforcedx-vscode/issues/1038

**Comment by ntotten** [comment]
Could you please capture the extension host logs: https://github.com/forcedotcom/salesforcedx-vscode/wiki/How-to-Collect-Performance-Information-for-Support#capture-extension-logs

That will help us diagnose the underlying problem.

**Comment by ad1969** [comment]
[vscode sfdx.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/2860872/vscode.sfdx.zip)

Nothing is coming up in the log. I uploaded a short movie to show you what is happening or not happening in this case. Here is are all my logs for the last 2 days:

> [2019-02-12 15:44:50.522] [exthost] [info] extension host started
> [2019-02-12 15:44:50.554] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.554] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\debug-auto-launch\dist\extension
> [2019-02-12 15:44:50.557] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.557] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\emmet\dist\extension
> [2019-02-12 15:44:50.561] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.561] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main
> [2019-02-12 15:44:50.583] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.583] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\merge-conflict\dist\extension
> [2019-02-12 15:44:50.587] [exthost] [info] ExtensionService#_doActivateExtension christian-kohler.path-intellisense {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.587] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\christian-kohler.path-intellisense-1.4.2\out\src\extension
> [2019-02-12 15:44:50.606] [exthost] [info] ExtensionService#_doActivateExtension CoenraadS.bracket-pair-colorizer {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.606] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\coenraads.bracket-pair-colorizer-1.0.61\out\src\extension
> [2019-02-12 15:44:50.634] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.634] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\dbaeumer.vscode-eslint-1.8.0\client\out\extension
> [2019-02-12 15:44:50.691] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.691] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\eamodio.gitlens-9.5.0\dist\extension
> [2019-02-12 15:44:50.726] [exthost] [info] ExtensionService#_doActivateExtension Equinusocio.vsc-material-theme {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.726] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\equinusocio.vsc-material-theme-2.7.0\out\src\material.theme.config
> [2019-02-12 15:44:50.745] [exthost] [info] ExtensionService#_doActivateExtension kisstkondoros.vscode-codemetrics {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.745] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\kisstkondoros.vscode-codemetrics-1.17.4\out\src\extension
> [2019-02-12 15:44:50.874] [exthost] [info] ExtensionService#_doActivateExtension PKief.material-icon-theme {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.874] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\pkief.material-icon-theme-3.6.3\out\src\extension
> [2019-02-12 15:44:50.947] [exthost] [info] ExtensionService#_doActivateExtension robertohuertasm.vscode-icons {"startup":true,"activationEvent":"*"}
> [2019-02-12 15:44:50.947] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\robertohuertasm.vscode-icons-8.1.0\out\src\
> [2019-02-12 15:44:51.039] [exthost] [info] ExtensionService#_doActivateExtension salesforce.salesforcedx-vscode-core {"startup":true,"activationEvent":"workspaceContains:sfdx-project.json"}
> [2019-02-12 15:44:51.039] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\dinua\.vscode\extensions\salesforce.salesforcedx-vscode-core-45.1.0\out\src
> [2019-02-12 15:44:53.609] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"activationEvent":"onLanguage:jsonc"}
> [2019-02-12 15:44:53.609] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\configuration-editing\dist\extension
> [2019-02-12 15:44:53.614] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"activationEvent":"onLanguage:jsonc"}
> [2019-02-12 15:44:53.614] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\client\dist\jsonMain
> [2019-02-12 15:44:53.628] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onLanguage:jsonc"}
> [2019-02-12 15:44:53.628] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension
> [2019-02-13 08:48:53.051] [exthost] [info] ExtensionService#_doActivateExtension vscode.html-language-features {"startup":false,"activationEvent":"onLanguage:html"}
> [2019-02-13 08:48:53.051] [exthost] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\client\dist\htmlMain
>

**Comment by ad1969** [comment]
Here is a short video of what is happening, or not happening in this case
[vscode sfdx.zip](https://github.com/forcedotcom/salesforcedx-vscode/files/2869707/vscode.sfdx.zip)

**Comment by lcampos** [comment]
@ad1969 after seeing your video it's still not clear what could be wrong. Could you attach a screenshot of the dev tools console after you run the command to see if there are any errors logged ? You can do this by going to Help > Toggle Developer Tools and then selecting the Console tab on it.

Also, could you provide which sfdx cli version you are on ? You can do this by running `sfdx --version` on the terminal.
