### ISSUE TITLE
LWC and Aura Language Servers crash 5x on start

### ISSUE THREAD

**Issue by mtetlow** [forcedotcom/salesforcedx-vscode#1267]
### Summary

I was happily developing away, then got an exception ( https://github.com/babel/babel/issues/8689 ), I tried upgrading sfdx to latest, I found a duplicate import statement in a lwc which seemed to resolve the error, but now I am just getting these crashes right when I open vscode for a project.

Is there any way to look at some logs to see what is causing the Aura and LWC language servers to crash?

### Steps To Reproduce:

1. Can't reproduce in a simple project. In my case I just get this error whenever I open the project in vscode:
![Screen Shot 2019-04-16 at 3 15 06 PM](https://user-images.githubusercontent.com/1168845/56248267-b3bcc600-6064-11e9-8e57-d485ea348729.png)

### Expected result

LWC and Aura Language servers start

### Actual result

LWC and Aura Language servers crash 5x then stop on open

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Version 1.33.1 (1.33.1)
**SFDX CLI Version**:
sfdx-cli/7.3.0-94ecf2d5ee darwin-x64 node-v10.15.3
**OS and version**:
macOS Mojave 10.14.1

**Comment by mtetlow** [comment]
I tried a simplified reproduction in a new minimal project and came up with nothing.

I also deleted the .sfdx/typings dir

**Comment by mtetlow** [comment]
any tips on debugging this? LWC dev is a lot slower without the language server :)

**Comment by Szandor72** [comment]
Hey @lcampos, 

for unforeseen reasons I am now temporarily on a mac which throws the error on lwc/aura language servers crashing.

Which details do I need to provide in order for you to tackle this easier?

mojave, 10.14.4 (18E227)
sfdx-cli/7.6.0-28071a499b darwin-x64 node-v10.15.3

**Comment by lcampos** [comment]
Hi @Szandor72 what version of the extensions are you on ? Is there anything particular about the project's shape or the components you're working on ? 

In case you have a project you can share with us, that would help us debug the issue and work on a fix. We've unfortunately haven't been able to replicate it on our side.

**Comment by jjTorrent** [comment]
I am also experiencing this issue with both Aura and LWC language servers.

Mac OS Mojave, 10.14.5 (18F132)
sfdx-cli/7.8.1-8f830784cc darwin-x64 node-v10.15.3
VS Code, Version 1.34.0 (1.34.0)
Extensions, version 45.15.1

**Comment by stephenwillcock** [comment]
I am also seeing the same problem with both Aura and LWC language servers, on trivial projects.

Mac OS Mojave, 10.14.5
VS Code Version 1.34.0
sfdx-cli/7.8.1-8f830784cc darwin-x64 node-v10.15.3
LWC/Aura extensions version 45.15.1

I seem to be able to work around the issue by downgrading the LWC/Aura extensions to 45.12.0

**Comment by nrkruk** [comment]
@stephenwillcock @jjTorrent @Szandor72 could one of you provide the url for a specific github repository you can reproduce this issue on? That would help me track down exactly what is happening

**Comment by jjTorrent** [comment]
@nrkruk 
[DevHubTest](https://github.com/jjTorrent/DevHubTest)

**Comment by stephenwillcock** [comment]
For me this occurs immediately after creating a [new SFDX project](https://github.com/stephenwillcock/sfdx-empty-project)

**Comment by jjTorrent** [comment]
@stephenwillcock 
Same here. Actually, it's with _all_ projects, for me.

**Comment by mtetlow** [comment]
@lcampos @nrkruk can you add any details on how we can generate a useful debug log when this occurs? This may get us closer to resolving it.

**Comment by Postem1** [comment]
Try to download/update your _python_ extension.  Might be a good idea to also look at other dependencies.

**Comment by jjTorrent** [comment]
@Postem1 
Not sure what you mean. I don't have a Python extension installed in VS Code. Can you clarify?

**Comment by Postem1** [comment]
@jjTorrent 
I was referring to the Python extension (created by Microsoft) in VS Code. 
Try downloading it and see if that helps.  It is a dependency for the Salesforce pack.

**Comment by jjTorrent** [comment]
@Postem1 
I wasn't aware of that. If it's a dependency, then why isn't it installed alongside the other dependent extensions for SF? Curious. Anyway, I'll give it a shot!

**Comment by jjTorrent** [comment]
@Postem1 
No change. The language servers continue to crash after installing the Python Extension for VS Code created by Microsoft.

**Comment by lcampos** [comment]
@jjTorrent @Postem1 the Salesforce extensions **do not** depend on any python extension. We are still looking into this and will update this thread once we have a fix ready. Sorry for the trouble this is currently causing.

**Comment by NightBijou** [comment]
Hi guys, same problem over here: I was getting the two errors "The Aura Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted." and "The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted." after opening a Salesforce DX project in Visual Studio Code. I did not have this problems from the start but I don't remember when they first showed up. After some trial and error, I found the culprit on my system, maybe this information can be helpful for others.

Windows 10 Build Enterprise Version 1803, Visual Studio Code 1.35.1, Salesforce Extension Pack 45.15.1 - May 17, 2019.

After removing "C:\Program Files (x86)\nodejs\" from my system path, the problem went away. This turned out to be a rather old version of nodejs, the command "npm version" gave me npm: '2.11.3' among other things. I think this installation came with Visual Studio (the real Visual Studio), which is also installed on my system. I am currently using version 2017. I then upgraded that installation by running an msi installer downloaded from https://nodejs.org/en/download/, added nodejs back to my system path, and it works now. The command "npm version" now returns npm: '6.9.0'. Hope this helps.

**Comment by sthornley** [comment]
@NightBijou's solution has fixed the errors on my system. Thanks!

**Comment by stephenwillcock** [comment]
Likewise - installing [Node 10.16.0](https://nodejs.org/en/download/) (5.4.1 to 6.9.0) fixed it for me
Thanks @NightBijou !

**Comment by jjTorrent** [comment]
Yes!!! I also updated npm via Terminal:
**npm** install **npm**@latest -g

**Comment by nrkruk** [comment]
PR is up with a fix - big thanks to @NightBijou for the useful info- helped me track down and reproduce the issue. This should be resolved in tomorrow's release of the plugins.

**Comment by NightBijou** [comment]
Hey everyone, I'm glad to see that the problem could be solved. @nrkruk Thanks for your quick response. This tool set is important to us, keep up the good work, I'm looking forward to seeing more cool stuff from you guys in the future.

**Comment by nrkruk** [comment]
Issue is now resolved in v46.1.0 of the extensions

**Comment by domonique-ncino** [comment]
I still get this error.

**Comment by cleverlemming** [comment]
I am seeing this issue today. Windows 10. Version 1.66.2

![image001](https://user-images.githubusercontent.com/165264/163433957-f0e7dc89-1c37-4261-80f2-fc0b557ece50.png)
![image002](https://user-images.githubusercontent.com/165264/163433958-844af40c-f351-45df-afbd-90de57499ce4.png)

**Comment by MattGarnettWelsh** [comment]
Still getting this issue today. 

On Windows 10 Enterprise, Node v16.16.0, NPM v8.11.0.

![image](https://user-images.githubusercontent.com/13387497/183081105-1eab6411-1adb-49bc-aba5-1014698c3f69.png)

**Comment by NagarjunaParala** [comment]
Still this is not resolved.

**Comment by ministe2003** [comment]
I've recently started getting this issue.  I've tried completely uninstalling sf, vscode, java, node and npm.  When I go through the process of reinstalling it comes back once I install the extended extension pack

Name: Salesforce Extension Pack (Expanded)
Id: salesforce.salesforcedx-vscode-expanded
Description: Extensions for developing on the Salesforce Platform
Version: 61.10.0
Publisher: Salesforce
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-expanded


Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Java:
C:\Program Files\Eclipse Adoptium\jdk-21.0.4.7-hotspot\bin\java.exe

sf:
@salesforce/cli: Updating CLI... already on version 2.55.6-648ad30

```
c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Invalid character in entity name
Line: 18656
Column: 37
Char:  
    at error (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\sax\lib\sax.js:684:7)
    at SAXParser.write (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\sax\lib\sax.js:1522:13)
    at exports.Parser.Parser.parseString (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\xml2js\lib\parser.js:5:59)
    at Typing.declarationsFromCustomLabels (c:\Users\My User\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.10.0\node_modules\@salesforce\lwc-language-server\lib\typing.js:68:47)

Node.js v20.14.0
[Error - 11:16:37 AM] Connection to server got closed. Server will not be restarted.
```
