### ISSUE TITLE
Refresh SObject definitions not working in 46.17.0 (also 47.1.0)

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/salesforcedx-vscode#1702]
### Summary

When i run SFDX Refersh SObject definitions against a developer edition org (not scratch, not sandbox), it fails

### Steps To Reproduce:

1.  Connect SFDX cli and Salesforce Extension pack to a developer edition org
1.  Run SFDX Refresh SObject definitions (there is now a new menu for all objects, custom or standard - for me all fail)

### Expected result

The SObject definitions are refreshed

### Actual result

The command fails

### Additional information

Error log:
```
Starting SFDX: Refresh SObject Definitions

14:34:48.623 sfdx sobject definitions refresh
Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.
14:34:53.478 sfdx sobject definitions refresh ended with error Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.

14:34:53.479 sfdx sobject definitions refresh ended with exit code 1
```
Starting SFDX: Refresh SObject Definitions

14:34:48.623 sfdx sobject definitions refresh
Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.
14:34:53.478 sfdx sobject definitions refresh ended with error Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.

14:34:53.479 sfdx sobject definitions refresh ended with exit code 1
```
Starting SFDX: Refresh SObject Definitions

14:40:21.581 sfdx sobject definitions refresh
Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.
14:40:26.996 sfdx sobject definitions refresh ended with error Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.

14:40:26.997 sfdx sobject definitions refresh ended with exit code 1
```

**VS Code Version**:
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z

**SFDX CLI Version**:
```
sfdx-cli/7.27.0-714f62f9c1 darwin-x64 node-v10.15.3
```

**OS and version**:
macOS 10.15 (19A583)

All other commands work fine, i can retrieve source, deploy it, run tests. So the Auth token is definitely valid.

**Comment by az-oolloow** [comment]
The issue is still present in 47.1.0

**Comment by RandyTrigg** [comment]
Thanks for logging this bug report @az-oolloow.  Looks like the issue is still present in 47.2.0.

**Comment by brpowell** [comment]
Hi all. Can you try selecting your default org again with the org picker? If that doesn't work, can you try reauthorizing your org? We'll keep looking into this.

**Comment by az-oolloow** [comment]
@brpowell selecting org again didn't work; re-authorising using the SFDX VS Code command did work (at least immediatelly after i did that i can refresh SObjects); will need to see if this is some token expiry issue and it will break again in a few hours/days. Thanks for the workaround though.

**Comment by az-oolloow** [comment]
@brpowell I checked a few hours later - it doesn't work again, although this time i got a different error:

```
Failure performing sObject describe [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]
14:07:02.774 sfdx sobject definitions refresh ended with error Failure performing sObject describe [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]
```

**Comment by brpowell** [comment]
Thanks for reporting @az-oolloow, we'll take a deeper look.

**Comment by VictorKilo** [comment]
I'm having the same issue where I receive the error message: `Failure performing sObject describe [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]`. 

Occasionally a series of random re-authentication steps will work, but I can't find a rhyme or reason to the ordering. 

In most cases restarting vscode solves the issue.

**Comment by RandyTrigg** [comment]
Could you say more about how you're doing re-authentication?  I can't seem
to get past the "Must pass a username..." error.  Here's what I tried (with
username and org id x'ed out).  What's the better way to re-authenticate
devhub?

Thanks,

Randy

Starting SFDX: Authorize a Dev Hub

14:46:22.299 sfdx force:auth:web:login --setdefaultdevhubusername
Successfully authorized xxxxxxxxxxxx with org ID xxxxxxxxxxxxx
You may now close the browser
14:46:35.417 sfdx force:auth:web:login --setdefaultdevhubusername
ended with exit code 0

Starting SFDX: Refresh SObject Definitions

14:46:51.726 sfdx sobject definitions refresh
Failure performing sObject describe Must pass a username and/or OAuth
options when creating an AuthInfo instance.
14:46:55.386 sfdx sobject definitions refresh ended with error Failure
performing sObject describe Must pass a username and/or OAuth options
when creating an AuthInfo instance.

14:46:55.387 sfdx sobject definitions refresh ended with exit code 1

**Comment by lcampos** [comment]
This is fixed in release `v47.4.0` of the extensions, thanks for reporting the issue and helping us debug it.

**Comment by RandyTrigg** [comment]
Thanks for working on this!  However, I must be missing something fundamental.  I am now in v47.4.0 of the SF extensions, and the other bits are also up to date.  I authorize my devhub, and then try to refresh sobject definitions.  Still getting that same error:

-----
Starting SFDX: Authorize a Dev Hub

14:22:49.975 sfdx force:auth:web:login --setdefaultdevhubusername
Successfully authorized xxxxxxx with org ID yyyyyyy
You may now close the browser
14:22:58.972 sfdx force:auth:web:login --setdefaultdevhubusername ended with exit code 0

Starting SFDX: Refresh SObject Definitions

14:23:09.965 sfdx sobject definitions refresh
Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.
14:23:13.475 sfdx sobject definitions refresh ended with error Failure performing sObject describe Must pass a username and/or OAuth options when creating an AuthInfo instance.

14:23:13.475 sfdx sobject definitions refresh ended with exit code 1
-----

Thanks, 

Randy

**Comment by RandyTrigg** [comment]
Okay, I finally figured out the re-authorize work-around for the error.  I can successfully refresh my sobject definitions when I first re-authorize like so:

sfdx force:auth:web:login --setalias DevHub --instanceurl https://login.salesforce.com --setdefaultusername

Thanks again @brpowell for fixing the bug.

**Comment by brpowell** [comment]
Glad you were unblocked @RandyTrigg. Let us know if you keep encountering the error and we can keep looking at it.
