### ISSUE TITLE
Apex Autocomplete issues due to performance problems

### ISSUE THREAD

**Issue by osieckiAdam** [forcedotcom/salesforcedx-vscode#2095]
**Summary:**

Autocomplete is not working for real-world examples

**Steps to reproduce:**
1. Open Salesforce project, with real class, used in production code. (few inner classes, more than 400 lines of code, classes extending other classes etc.)
2. Type something and wait for the autocomplete

**Expected Result**
Should show autocomplete or snippet suggestion

**Actual Result**
No autocomplete suggestion usually even after few minutes

**Additional information**
VS Code Version: 1.43.1
SFDX CLI Version: 7.50.0-9030e49cbb
OS and version: Windows 10 Pro N, Version 1903

I started using salesforcedx-vscode extension on a project which is medium-sized (apex code limit is used in ~37%) and I realised that autocompletion works fine only for smaller, less-complicated classes. I'm able to use autocompletion in helpers, utils classes which are sets of static methods. But when I'm trying to use autocomplete in class with few inner classes, which are extending abstract or virtual classes, then I don't get any autocomplete options, even if they are not big (400 - 500 lines of code).
What is more, snippets for these classes are also not working, suggestions are showing after a few minutes of waiting. 

I tried increasing the amount of memory allocation to the Apex Language Server: 
"salesforcedx-vscode-apex.java.memory": 8192
And it's still not working, Java Platform SE binary process is not even consuming that amount of memory, it uses up to 4700 - 4900 MB.

I also tried installing different Java binaries and the result is the same.
There are no logs in Apex Language Server, it just seems like it is responding extremely slowly

Is this kind of known limitation of the extension? Are there other ways to make this work in medium or large projects?

**Comment by smaddox-sf** [comment]
Hi @osieckiAdam - Thanks for raising this.  Do you have an example repo you can share with us where you see this behavior?  We'll try to replicate to see if we can pin down the problem you are experiencing.

From your description, it sounds like you are getting autocompletion results some of the time  and so I assume you have already used the `SFDX: Refresh SObject Definitions`.   (correct me if I'm wrong on that)

**Comment by osieckiAdam** [comment]
Hi @smaddox-sf, unfortunately, I can't share the repo where I see it, the biggest open-source repos that I know are:
https://github.com/SalesforceFoundation/NPSP
https://github.com/SalesforceFoundation/EDA
I can try to reproduce the issue on them in my free time

Yes, I get the autocompletion in smaller classes and I already Refreshed SObject Definition, so it works as expected, it just looks like a performance issue. It also looks like it's not related to my system configuration or any external conditions, because in the meantime I talked about this issue with a lot of people and all of them confirmed my observation that it works well only for a small codebase. Please let me know if You need any further details.

Thank You for taking care of this issue, I really like Your extension, it's getting better and better every release and I think that You are doing really great job here, but this performance issue is really making my work harder. I'm keeping my fingers crossed for You!

**Comment by smaddox-sf** [comment]
Thanks for the additional input @osieckiAdam!  We will investigate this

**Comment by sfsholden** [comment]
Hi @osieckiAdam, thank you for the info provided thus far. If possible, please also provide the following:

1. Logs from `Output > Apex Language Server`
2. Rough estimate on how many inner classes are in the Apex Class that is experiencing completion performance issues
3. Rough estimate on how many total fields are included in those inner classes

**Comment by osieckiAdam** [comment]
**1. Log:**
15:09:07.863 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
kwi 25, 2020 3:09:08 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075527 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 35 ms.
15:09:19.217 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
15:09:19.258 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
15:09:21.518 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 13655 ms.
15:09:21.524 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
15:10:10.870 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types took 49210 ms.
kwi 25, 2020 3:13:05 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 54
kwi 25, 2020 3:17:48 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 106
kwi 25, 2020 3:20:09 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 213
kwi 25, 2020 3:20:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 215
kwi 25, 2020 3:20:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 218
kwi 25, 2020 3:27:49 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 377
kwi 25, 2020 3:27:52 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 380
kwi 25, 2020 3:27:52 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 379
kwi 25, 2020 3:27:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 384
kwi 25, 2020 3:27:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 383

my comment: line 'WARNING: Unmatched cancel notification for request id 383' is not showing if I'm waiting until autocomplete is finished.

**2. I have two examples:**
- Class with 52 inner classes: huge delay +/- 3 minutes
- Class with 12 inner classes: small delay, up to 3-4 seconds
Unfortunately I don't have any examples between that range. If You need any example of class which can cause some trouble You can get this repo: https://github.com/afawcett/apex-toolingapi and try to add anything to ToolingAPIWSDL class

**3.** Inner classes are extending virtual classes, so there are usually 4 levels of extending. 
Almost always we have the same total number of fields, methods, and constructiors in our classes and it will be:
- 4 fields
- 20 methods
- 1 constructor

**Comment by lcampos** [comment]
Hi, want to provide an update on this. Yesterday we released some changes in version `48.19.0` of the extensions that address some of the performance issues highlighted here. I'd ask for you to take a look a them and let us know how they work with your project. We'll keep working on follow up enhancements but would appreciate having some feedback in case there's something else we need to add to the list of things we're tackling. Thanks for the feedback and partnering with us on getting this fixed.

**Comment by osieckiAdam** [comment]
Hey, thanks for following us up on this topic. 

I did some quick check-up on the same examples which I was talking about in one of the previous post. 
_(Class with 52 inner classes: huge delay +/- 3 minutes
Class with 12 inner classes: small delay, up to 3-4 seconds)_
Now I see improvement in the big class, I'm waiting between 45-50 seconds to see the autocompletion, which is still not enough but we can clearly see that we are moving in the right direction. Suprisingly I didn't see any improvment in the example with smaller class.
What is more I have an impression that navigation is much faster and its working in much more cases (but I don't have any benchmark for this, I didn't check it in previous version of the extension)
One suggestion from my side: I think that for built in classes and namespaces there should be some kind of cache which could provide immediate response, because options will always be the same no matter how big project is, and what is the context, so if I'm typing 'System.' or 'Database.' I would like to see options quickly

**Comment by sfsholden** [comment]
@osieckiAdam Thanks again for the feedback and the example provided. It was very helpful.

I'd like to get some more details for the completions mentioned above. In this last release we also added some statistics that can be enabled for completions.

Please add the following to your `settings.json` and reload the VSCode window. Statistics should now print to the Output panel for Apex Language Server:
"salesforcedx-vscode-apex.advanced.enable-completion-statistics": "true"

Please paste your results. And thank you for all your help in improving the completions.

**Comment by osieckiAdam** [comment]
Hey, this is the full output (with initial logs) for the second example (the one with smaller number of inner classes). First I tried to get autocompletion for methods in another custom class, and next I tried to get autocompletion from Database class:

21:47:31.544 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types.
cze 08, 2020 9:47:33 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075527 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 16 ms.
21:47:42.508 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Patching standard library for System.Database.* methods
21:47:42.524 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Done patching standard library for System.Database.* methods
21:47:45.294 [Apex Prelude Service STARTING] INFO  a.j.l.i.s.ApexPreludeManagedService - Scanning built-in and system Apex types took 13715 ms.
21:47:45.296 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types.
cze 08, 2020 9:48:52 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 1
cze 08, 2020 9:48:52 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 2
21:49:37.384 [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types took 111950 ms.
cze 08, 2020 9:49:48 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 23
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/BookingChangeHandlers.cls took 2512 ms.
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 734; Number of Items Added: 0
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 188; Number of Items Added: 0
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 561; Number of Items Added: 0
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:49:50.672 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 157; Number of Items Added: 1
21:49:50.673 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 236; Number of Items Added: 0
21:49:55.270 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/BookingChangeHandlers.cls took 8214 ms.
21:49:55.272 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 5; Number of Items Added: 3
21:49:55.273 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 157; Number of Items Added: 4
21:49:55.274 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 6361; Number of Items Added: 19
21:49:55.275 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 228; Number of Items Added: 0
21:49:55.275 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 217; Number of Items Added: 74
21:49:55.275 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 202; Number of Items Added: 2
21:49:55.275 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:49:55.275 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:49:55.276 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 122; Number of Items Added: 1
21:49:55.277 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 280; Number of Items Added: 0
cze 08, 2020 9:49:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 39
cze 08, 2020 9:49:58 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 43
cze 08, 2020 9:49:58 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 42
cze 08, 2020 9:49:58 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 45
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/BookingChangeHandlers.cls took 13616 ms.
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 3
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 143; Number of Items Added: 4
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 9773; Number of Items Added: 19
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 920; Number of Items Added: 0
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 388; Number of Items Added: 74
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 1259; Number of Items Added: 2
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:50:09.268 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:50:09.269 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 128; Number of Items Added: 1
21:50:09.270 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 545; Number of Items Added: 0
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/BookingChangeHandlers.cls took 11444 ms.
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 10235; Number of Items Added: 169
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 148; Number of Items Added: 2
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 172; Number of Items Added: 0
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 99; Number of Items Added: 1
21:50:10.313 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 180; Number of Items Added: 0
cze 08, 2020 9:51:29 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 71
cze 08, 2020 9:51:29 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 74
cze 08, 2020 9:51:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 77
cze 08, 2020 9:51:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 76
21:51:36.805 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/BookingChangeHandlers.cls took 9941 ms.
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 3
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 139; Number of Items Added: 4
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 7927; Number of Items Added: 19
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 392; Number of Items Added: 0
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 202; Number of Items Added: 206
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 583; Number of Items Added: 4
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 133; Number of Items Added: 1
21:51:36.806 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 208; Number of Items Added: 0
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/BookingChangeHandlers.cls took 6965 ms.
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 5838; Number of Items Added: 80
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 157; Number of Items Added: 22
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 176; Number of Items Added: 0
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 119; Number of Items Added: 1
21:51:37.452 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 183; Number of Items Added: 0

**Comment by osieckiAdam** [comment]
First example (bigger class). Here I was looking for autocompletion from Database class, and it went much faster than yesterday, I'm not sure what is the reason for such a big difference:

WARNING: Unmatched cancel notification for request id 161
cze 08, 2020 9:57:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 160
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/TaskChangeCustomersHandlers.cls took 11966 ms.
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 7011; Number of Items Added: 80
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 962; Number of Items Added: 22
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 1564; Number of Items Added: 0
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 135; Number of Items Added: 1
21:58:11.696 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 867; Number of Items Added: 0
21:58:17.012 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/TaskChangeCustomersHandlers.cls took 22333 ms.
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 2364; Number of Items Added: 3
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 1458; Number of Items Added: 4
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 12721; Number of Items Added: 19
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 1556; Number of Items Added: 0
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 706; Number of Items Added: 206
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 1025; Number of Items Added: 4
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 106; Number of Items Added: 1
21:58:17.013 [ForkJoinPool.commonPool-worker-1] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 896; Number of Items Added: 0

Another attempt of looking for Database class completion:
cze 08, 2020 10:01:04 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 189
cze 08, 2020 10:01:08 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 193
22:01:25.680 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/TaskChangeCustomersHandlers.cls took 21078 ms.
22:01:25.680 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 13583; Number of Items Added: 80
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 1021; Number of Items Added: 22
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 3509; Number of Items Added: 0
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 181; Number of Items Added: 1
22:01:25.682 [ForkJoinPool.commonPool-worker-7] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 1576; Number of Items Added: 0
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/TaskChangeCustomersHandlers.cls took 29684 ms.
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 2407; Number of Items Added: 4
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 6569; Number of Items Added: 4
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 14642; Number of Items Added: 26
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 1006; Number of Items Added: 0
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 750; Number of Items Added: 206
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 695; Number of Items Added: 4
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 100; Number of Items Added: 1
22:01:30.716 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 1141; Number of Items Added: 0

So its taking 20-25 seconds now.

**Comment by osieckiAdam** [comment]
Bigger class again, now I'm looking for autocompletion from another custom class:

cze 08, 2020 10:03:24 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 220
cze 08, 2020 10:03:25 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 223
cze 08, 2020 10:03:30 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 226
cze 08, 2020 10:03:31 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 230
22:03:59.017 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/TaskChangeCustomersHandlers.cls took 38879 ms.
22:03:59.017 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 1638; Number of Items Added: 4
22:03:59.017 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 2636; Number of Items Added: 4
22:03:59.017 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 24821; Number of Items Added: 26
22:03:59.017 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 2476; Number of Items Added: 0
22:03:59.017 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 1269; Number of Items Added: 74
22:03:59.017 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 2179; Number of Items Added: 2
22:03:59.018 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:03:59.018 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:03:59.019 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 139; Number of Items Added: 1
22:03:59.019 [ForkJoinPool.commonPool-worker-3] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 1202; Number of Items Added: 0
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Completions for file:///c:/Users/Britenet/Documents/Repos/EF_DEV/force-app/main/default/classes/TaskChangeCustomersHandlers.cls took 31638 ms.
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: LocalVariableNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: FieldNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MethodNamesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: MembersCompletionStrategy; Time Taken [ms]: 27616; Number of Items Added: 169
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TypesCompletionStrategy; Time Taken [ms]: 702; Number of Items Added: 2
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SystemNamespaceCompletionStrategy; Time Taken [ms]: 730; Number of Items Added: 0
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerKeywordCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: TriggerContextVariablesCompletionStrategy; Time Taken [ms]: 0; Number of Items Added: 0
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SoqlSnippetCompletionStrategy; Time Taken [ms]: 95; Number of Items Added: 1
22:04:01.766 [ForkJoinPool.commonPool-worker-5] INFO  a.j.l.i.c.ApexCompletionStrategyAggregator - Strategy: SObjectFieldNamesCompletionStrategy; Time Taken [ms]: 940; Number of Items Added: 0

**Comment by sfsholden** [comment]
@osieckiAdam Thanks for the info, that is helpful. I'm sorry these changes didn't trim out more of the time for the completions.

Would you be willing to print some completion statistics using the example repo https://github.com/afawcett/apex-toolingapi? I'm wondering what kind of numbers you'll see.

**Comment by adamOsieckiBtn** [comment]
hey @sfsholden, sorry for not responding to You, apparently I missed the notification
I checked the numbers at the same example as You used here: https://github.com/forcedotcom/salesforcedx-vscode/pull/2230
First conclusion is that my numbers are much worse than Yours:
![image](https://user-images.githubusercontent.com/36951505/85465135-b8ee9c80-b5a8-11ea-815c-32158f6807e9.png)
- [ApexIndexer STARTING] INFO  a.jorje.lsp.impl.index.ApexIndexer - ApexIndexer: Scanning user-defined types took 1029ms (at Your example) vs 22400ms in my case (sometimes it could even be 43000ms
- INFO: Deduped array ApexLexer.DFA22_transition. Found 7075527 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 11ms (Your example) and mine is the same - 12ms

![example](https://user-images.githubusercontent.com/36951505/85467872-07516a80-b5ac-11ea-9cd2-219e69fd0a87.gif)
I tried to do exactly what You did on gif in the PR and the output was this error:
23:42:01.285 [ForkJoinPool.commonPool-worker-1] ERROR a.j.l.i.c.CodeActionsProviderAggregator - Encountered an error with code action provider apex.jorje.lsp.impl.codeActions.ApexCodeActionsProvider@55e7a35c
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at apex.jorje.lsp.impl.codeActions.ExtractConstantHandler.getNewVariableDeclaration(ExtractConstantHandler.java:152)
	at apex.jorje.lsp.impl.codeActions.ExtractConstantHandler.getNewStatementTextEdit(ExtractConstantHandler.java:136)
	at apex.jorje.lsp.impl.codeActions.ExtractConstantHandler.getCodeAction(ExtractConstantHandler.java:122)
	at apex.jorje.lsp.impl.visitors.CodeActionVisitor.getCodeActionExtractConstant(CodeActionVisitor.java:320)
	at apex.jorje.lsp.impl.visitors.CodeActionVisitor.visitEnd(CodeActionVisitor.java:141)
	at apex.jorje.lsp.impl.visitors.CodeActionVisitor.visitEnd(CodeActionVisitor.java:38)
	at apex.jorje.semantic.ast.expression.LiteralExpression.traverse(LiteralExpression.java:55)
	at apex.jorje.semantic.ast.expression.MethodCallExpression.traverse(MethodCallExpression.java:154)
	at apex.jorje.semantic.ast.statement.ExpressionStatement.traverse(ExpressionStatement.java:53)
	at apex.jorje.semantic.ast.statement.BlockStatement.traverse(BlockStatement.java:140)
	at apex.jorje.semantic.ast.statement.MethodBlockStatement.traverse(MethodBlockStatement.java:75)
	at apex.jorje.semantic.ast.member.Method.traverse(Method.java:104)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:129)
	at apex.jorje.semantic.ast.compilation.UserClass.traverse(UserClass.java:120)
	at apex.jorje.lsp.impl.codeActions.ApexCodeActionsProvider.getCodeActions(ApexCodeActionsProvider.java:69)
	at apex.jorje.lsp.impl.codeActions.BaseCodeActionsProvider.lambda$provideCodeActions$0(BaseCodeActionsProvider.java:79)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at apex.jorje.lsp.impl.codeActions.BaseCodeActionsProvider.provideCodeActions(BaseCodeActionsProvider.java:77)
	at apex.jorje.lsp.impl.codeActions.CodeActionsProviderAggregator.lambda$provideCodeActions$0(CodeActionsProviderAggregator.java:59)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at apex.jorje.lsp.impl.codeActions.CodeActionsProviderAggregator.provideCodeActions(CodeActionsProviderAggregator.java:57)
	at apex.jorje.lsp.impl.services.StandardTextDocumentService.lambda$codeAction$7(StandardTextDocumentService.java:291)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
cze 23, 2020 11:42:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 51
cze 23, 2020 11:42:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 52
cze 23, 2020 11:42:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 55
cze 23, 2020 11:42:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 56
cze 23, 2020 11:42:02 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 54

**Comment by adamOsieckiBtn** [comment]
I also checked less challenging example: 
![example2](https://user-images.githubusercontent.com/36951505/85469728-53051380-b5ae-11ea-8660-50f82378cb50.gif)

**Comment by ericmiller-toast** [comment]
Happy new year. Has there been any update on this, I'm getting the same error, and auto complete is not or stops working. 
I have attached the log of the error 
[VSCode-Apex Prelude Service.log](https://github.com/forcedotcom/salesforcedx-vscode/files/5838551/VSCode-Apex.Prelude.Service.log)

**Comment by jag-sfdc** [comment]
@ericmiller-toast - We have made several performance improvements recently to address Apex autocomplete performance issues. We are working on more improvements in the coming releases. Please let us know if you are still seeing this issue. Thanks!

**Comment by osieckiAdam** [comment]
@jag-sfdc why did you add 'more information required'? We delivered an example using ToolingAPI, you can literally do exactly the same test as I did as a benchmark and see if the delay is acceptable now, what more information is required?

**Comment by jag-sfdc** [comment]
@osieckiAdam - You are right and I think we have all the information to verify the behavior. Thanks for your reply!

**Comment by diyer** [comment]
Closing this old bug as several performance improvements have been made in this area and the issue is no longer reproducible. Please open a new issue if this reproduces with the latest vscode extensions version
