### ISSUE TITLE
Can't run "SFDX: Push" when the default SO is one that I didn't create

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/salesforcedx-vscode#2738]
### Summary

I have a friend's Scratch Org (SO) connected on my sfdx and when I set it as the default one VSCode does not show the Push Command. But when I switch back to one that I created the push command appears.

### Steps To Reproduce:

1.  Connect a Scratch Org that you did not create
2.  Set it as the default scratch org for your project
3. Ctrl+shift+p and search for the  extension's sfdx push command and verify it is not there
4.  Change the default scratch org for one that you created
5. Ctrl+shift+p and search again for the extension's sfdx push command and verify it is now showing up

### Expected result

The vscode SFDX Push command should appear whenever you have a SO selected as the default and when you are inside an sfdx project.

### Actual result

The Vscode SFDX Push command does not show for SO that the user did not create, even when it is authenticated and known by sfdx.

### Additional information

**VS Code Version**: 

**SFDX CLI Version**: sfdx-cli/7.78.1-5a65d9dd2f win32-x64 node-v12.18.3

**OS and version**: Windows 10

**Comment by AnanyaJha** [comment]
Hi @AllanOricil thanks for reporting this! How did you connect to your friend's scratch org? The org picker in VS Code will only display scratch orgs associated with your default dev hub. To use a scratch org you didn't create (and see the push/pull commands), you'll need to log into the dev hub associated with that scratch org and set that as your default dev hub. To authorize the new dev hub, use the org picker in the bottom toolbar. Let me know if you have any questions!

**Comment by AllanOricil** [comment]
> Hi @AllanOricil thanks for reporting this! How did you connect to your friend's scratch org? The org picker in VS Code will only display scratch orgs associated with your default dev hub. To use a scratch org you didn't create (and see the push/pull commands), you'll need to log into the dev hub associated with that scratch org and set that as your default dev hub. To authorize the new dev hub, use the org picker in the bottom toolbar. Let me know if you have any questions!

I authorized her Scratch Org on my sfdx using the credentials she generated on her side.
I noticed I can do a source push command without any problems using the cli. Is just the VSCode Extension that does not allow me to do so. Also, the extension shows her SO set as my default one, so the extension knows her Scratch Org. It is just that it can't perform the push command with it.

Vscode extension knows about her Scratch Org
![image](https://user-images.githubusercontent.com/55927613/99660552-697aa280-2a5a-11eb-9d37-a5e52eeb491c.png)

Scratch Org is connected but does not show as one of mine
![image](https://user-images.githubusercontent.com/55927613/99660548-67b0df00-2a5a-11eb-82e2-b2860a87f3ec.png)

Couple of pushes I did through the sfdx cli to her Scratch Org
![image](https://user-images.githubusercontent.com/55927613/99660580-77302800-2a5a-11eb-8a75-3b8a8f7cec16.png)


I think you just need to change enable all Scratch Orgs to use the Push Command extension and not just the ones I created. Maybe you are getting the list of SO from the ones created by the user and not all the SO available.

**Comment by AnanyaJha** [comment]
Hi @AllanOricil we tried to reproduce your issue by creating a scratch org, switching to a different dev hub (user), then setting the default org to the unrelated scratch org using the CLI, and we actually _did_ see the `Push` and `Pull` commands in VS Code. Could you share the contents of your `sfdx-config.json` file when you're connected to your friend's scratch org?
It looks like you're on the latest version of the CLI, could you also tell us which version of the Salesforce Extensions you're using?

**Comment by AllanOricil** [comment]
> Hi @AllanOricil we tried to reproduce your issue by creating a scratch org, switching to a different dev hub (user), then setting the default org to the unrelated scratch org using the CLI, and we actually _did_ see the `Push` and `Pull` commands in VS Code. Could you share the contents of your `sfdx-config.json` file when you're connected to your friend's scratch org?
> It looks like you're on the latest version of the CLI, could you also tell us which version of the Salesforce Extensions you're using?

In the picture below you can see my sfdx and vscode extension versions.

![image](https://user-images.githubusercontent.com/55927613/99703146-abbdd700-2a8e-11eb-8804-e870c8f93594.png)

**Comment by AnanyaJha** [comment]
Thanks @AllanOricil! Can you also post the output to `sfdx force:config:get defaultdevhubusername`?

**Comment by AllanOricil** [comment]
> Thanks @AllanOricil! Can you also post the output to `sfdx force:config:get defaultdevhubusername`?

@AnanyaJha  dont consider that weird error message after updating sfdx cli. That will be another bug I will open haha

![image](https://user-images.githubusercontent.com/55927613/99706078-76b38380-2a92-11eb-858c-3829280e16aa.png)

**Comment by AnanyaJha** [comment]
Hi @AllanOricil we're still working on reproducing this issue- can you confirm how you logged into your friend's org? We tried the following process:
1. I created a scratch org and created a scratch org user for my friend to use. 
2. Went into the scratch org and changed the email address so she was able to generate a password for her scratch org user
2. She changed the password and auth'd into the scratch org user with the custom login url that was generated when i created a scratch org user

After this process, she does not see the Push/Pull commands in VS Code _and_ the CLI. Is this the same process you used for your friend's scratch org?
cc @sfsholden

**Comment by AllanOricil** [comment]
> Hi @AllanOricil we're still working on reproducing this issue- can you confirm how you logged into your friend's org? We tried the following process:
> 
> 1. I created a scratch org and created a scratch org user for my friend to use
> 2. Went into the scratch org and changed the email address so she was able to generate a password for her scratch org user
> 3. She changed the password and auth'd into the scratch org user with the custom login url that was generated when i created a scratch org user
> 
> After this process, she does not see the Push/Pull commands in VS Code _nor_ the CLI. Is this the same process you used for your friend's scratch org?
> cc @sfsholden

@AnanyaJha 

My friend and I are using the same devhuborg. She is connected to this devhub with her user and I with mine.
She created one Scratch Org, then generated the username and password using the CLI `sfdx force:user:password:generate -u HER_SCRATCH_ORG_USERNAME`
Then she gave the password and username to me.
From inside that sfdx project on the images I posted here, I ran `sfdx force:auth:web:login` but using the VSCode Extension Command, instead of typing the command.
Vscode Opened the browser and I entered the credentials she gave to me.
The authentication worked without a problem and her Scratch Org was now registered on my SFDX.
I connected to her Scratch Org because I needed to push some code changes I did in that sfdx project. After connecting I tried to ru the Vscode Extension Push Command and I noticed it was not showing up. Then I had to used `sfdx force:source:push -u nina_so_2 -f` and it worked. And this was the moment I understood something weird was happening.

**Comment by AllanOricil** [comment]
@AnanyaJha 
I think I discovered the issue. Her scratch org was registered as a "nonScratchOrg". But as I told before, I can run `sfdx force:source:push` without any problem and It is a Scratch Org! Maybe the VScode Extension is using the list of "nonScratchOrgs" to determine if it should or not show the Push command, which in this case shown bellow would break this logic. What do you think?

Obs: I deleted some information in the output below for protection.

````json
{
  "status": 0,
  "result": {
    "nonScratchOrgs": [
      {
        "username": "allanoricil@resourceful-raccoon-425098.com",
        "clientId": "PlatformCLI",
        "isDevHub": true,
        "lastUsed": "2020-11-20T12:30:00.287Z",
        "connectedStatus": "Connected"
      },
      {
        "username": "allanoricil@outlook.com",
        "clientId": "PlatformCLI",
        "isDevHub": true,
        "alias": "allandevhub",
        "lastUsed": "2020-11-20T12:30:00.288Z",
        "connectedStatus": "Connected"
      },
      {
        "username": "test-eizjxrgpwekh@example.com",
        "clientId": "PlatformCLI",
        "isDevHub": false,
        "alias": "nina_so_2",
        "lastUsed": "2020-11-20T12:30:00.289Z",
        "isDefaultUsername": true,
        "connectedStatus": "Connected",
        "defaultMarker": "(U)"
      },
      {
        "username": "allanoricilcos@playful-raccoon-nx63l4.com",
        "clientId": "PlatformCLI",
        "isDevHub": true,
        "alias": "org33",
        "lastUsed": "2020-11-20T12:30:00.288Z",
        "connectedStatus": "Connected"
      },
      {
        "username": "allan.oricil@hpe.com",
        "clientId": "PlatformCLI",
        "isDevHub": true,
        "alias": "pro_dev_hub",
        "lastUsed": "2020-11-20T12:30:00.287Z",
        "isDefaultDevHubUsername": true,
        "connectedStatus": "Connected",
        "defaultMarker": "(D)"
      },
      {
        "username": "allan.oricil@hpe.com.cep",
        "clientId": "PlatformCLI",
        "isDevHub": true,
        "alias": "pro_dev_hub_2",
        "lastUsed": "2020-11-20T12:30:00.287Z",
        "connectedStatus": "Connected"
      },
      {
        "username": "allanoricilcos@outlook.com.org31",
        "clientId": "PlatformCLI",
        "alias": "trailhead-org31",
        "lastUsed": "2020-11-20T12:30:00.288Z",
        "connectedStatus": "Connected"
      },
      {
        "username": "allanoricilcos@brave-otter-2vatv.com",
        "clientId": "PlatformCLI",
        "isDevHub": false,
        "alias": "trailhead36",
        "lastUsed": "2020-11-20T12:30:00.288Z",
        "connectedStatus": "Connected"
      }
    ],
    "scratchOrgs": [
      {
        "username": "test-0mf6pphe2osh@example.com",
        "createdOrgInstance": "CS95",
        "created": "1603988763494",
        "devHubUsername": "allanoricil@resourceful-raccoon-425098.com",
        "expirationDate": "2020-11-05",
        "isDevHub": false,
        "lastUsed": "2020-11-20T12:30:00.288Z",
        "status": "Expired",
        "isExpired": true,
        "signupUsername": "test-0mf6pphe2osh@example.com",
        "createdBy": "allanoricil@resourceful-raccoon-425098.com",
        "createdDate": "2020-10-29T16:25:51.000+0000",
        "attributes": {
          "type": "ScratchOrgInfo",
          "url": "/services/data/v50.0/sobjects/ScratchOrgInfo/2SR4o000000Cc37GAC"
        },
        "orgName": "my company",
        "edition": "Developer",
        "connectedStatus": "Unknown"
      },
      {
        "username": "test-i6xei9pqil5e@example.com",
        "clientId": "PlatformCLI",
        "createdOrgInstance": "CS78",
        "created": "1604999106445",
        "devHubUsername": "allan.oricil@hpe.com",
        "isDevHub": false,
        "expirationDate": "2020-11-17",
        "alias": "aoricil_so_1",
        "lastUsed": "2020-11-20T12:30:00.289Z",
        "status": "Expired",
        "isExpired": true,
        "signupUsername": "test-i6xei9pqil5e@example.com",
        "createdBy": "allan.oricil@hpe.com.prod",
        "createdDate": "2020-11-10T09:04:53.000+0000",
        "attributes": {
          "type": "ScratchOrgInfo",
          "url": "/services/data/v50.0/sobjects/ScratchOrgInfo/2SR1V0000008OTDWA2"
        },
        "orgName": "HPE DCE",
        "edition": "Developer",
        "connectedStatus": "Unknown"
      },
      {
        "username": "test-pjbgbaywtwqo@example.com",
        "clientId": "PlatformCLI",
        "createdOrgInstance": "CS95",
        "created": "1602757876390",
        "devHubUsername": "allan.oricil@hpe.com.cep",
        "isDevHub": false,
        "expirationDate": "2020-10-22",
        "lastUsed": "2020-11-20T12:30:00.289Z",
        "status": "Expired",
        "isExpired": true,
        "signupUsername": "test-pjbgbaywtwqo@example.com",
        "createdBy": "allan.oricil@hpe.com.cep",
        "createdDate": "2020-10-15T10:31:01.000+0000",
        "attributes": {
          "type": "ScratchOrgInfo",
          "url": "/services/data/v50.0/sobjects/ScratchOrgInfo/2SR2T000000L0MdWAK"
        },
        "orgName": "HPESC",
        "edition": "Developer",
        "connectedStatus": "Unknown"
      },
      {
        "username": "test-wnsdyzqjli9a@example.com",
        "clientId": "PlatformCLI",
        "createdOrgInstance": "CS78",
        "created": "1603893306721",
        "devHubUsername": "allan.oricil@hpe.com.cep",
        "expirationDate": "2020-11-04",
        "isDevHub": false,
        "lastUsed": "2020-11-20T12:30:00.288Z",
        "status": "Expired",
        "isExpired": true,
        "signupUsername": "test-wnsdyzqjli9a@example.com",
        "createdBy": "allan.oricil@hpe.com.cep",
        "createdDate": "2020-10-28T13:54:55.000+0000",
        "attributes": {
          "type": "ScratchOrgInfo",
          "url": "/services/data/v50.0/sobjects/ScratchOrgInfo/2SR2T000000L0TtWAK"
        },
        "orgName": "Demo company",
        "edition": "Developer",
        "connectedStatus": "Unknown"
      },
      {
        "username": "test-wu0mh91gexxa@example.com",
        "clientId": "PlatformCLI",
        "createdOrgInstance": "CS52",
        "created": "1603966535469",
        "devHubUsername": "allanoricil@outlook.com",
        "expirationDate": "2020-11-05",
        "lastUsed": "2020-11-20T12:30:00.289Z",
        "status": "Expired",
        "isExpired": true,
        "signupUsername": "test-wu0mh91gexxa@example.com",
        "createdBy": "allanoricil@outlook.com",
        "createdDate": "2020-10-29T10:15:21.000+0000",
        "attributes": {
          "type": "ScratchOrgInfo",
          "url": "/services/data/v50.0/sobjects/ScratchOrgInfo/2SR4p000000NZKcGAO"
        },
        "orgName": "my company",
        "edition": "Developer",
        "connectedStatus": "Unknown"
      }
    ]
  }
}

````

**Comment by AnanyaJha** [comment]
Hi @AllanOricil thanks for all the info! We attempted to reproduce the issue by going through the same steps you mentioned above (creating two dev hub users & using the generated scratch org pwd to log in from the second dev hub user), but we are correctly seeing the `Push/Pull` commands in VS Code. It seems like the issue may be with the specific scratch org you're attempting to use. Which auth file is the screenshot from, where are you seeing the `nonScratchOrgs` section? 
We aren't using the `nonScratchOrgs` attribute when determining whether an org is scratch org; we check for the presence of a `devhubUsername` attribute in the auth info for the scratch org. If there is an associated `devhubUsername`, then it's a scratch org and the `Push/Pull` commands will be displayed. In the `.sfdx` folder in your home directory, open up the auth file associated with the scratch org you're working with. There should be a field for `devhubUsername` as such:

<img width="385" alt="Screen Shot 2020-11-20 at 11 25 04 AM" src="https://user-images.githubusercontent.com/21326913/99830826-dc038500-2b23-11eb-911f-85527301f06b.png">

**Comment by AllanOricil** [comment]
> you

@AnanyaJha 
This is the content of that file you asked. I just changed the accessToken and refreshToken to use a random, non usable, code.

````json
{
    "orgId": "00D3D0000003PlcUAE",
    "accessToken": "9a0511de65229e046fe77493276e553196c40d6a7a7c5e123d027b40775f4764c695400d8982b1a7b5fd7eb7a2f3ed:65015ddc94997cff9a602499d8da5bdd",
    "refreshToken": "555ff975fb1850dc6695d3f:ce46366f0d67d600493e17b2e8fa6053",
    "instanceUrl": "https://page-dream-9422-dev-ed.cs70.my.salesforce.com",
    "loginUrl": "https://test.salesforce.com/",
    "username": "test-eizjxrgpwekh@example.com",
    "clientId": "PlatformCLI",
    "isDevHub": false
}
````

You can confirm that the credentials above are for the right SO in the images below.

![image](https://user-images.githubusercontent.com/55927613/100209052-5015a280-2f01-11eb-85aa-5c7481c8a98a.png)

**Comment by AnanyaJha** [comment]
@AllanOricil Thanks! Can you try adding in this line to the auth file for the scratch org `"devHubUsername": "yourdevhub"? When you authorize a new scratch org, the CLI should be adding in a `devHubUsername` field to indicate what dev hub the scratch org is associated with. Ideally, reauthorizing should fix the problem but we can try manually adding the needed data too.

**Comment by AllanOricil** [comment]
@AnanyaJha it worked. Here is what I did:

## 1st Test
1 - Manually added a <b>REAL</b> devhubusername to the devHubUsername prop in that file, as shown below:
````json
{
    "orgId": "00D3D0000003PlcUAE",
    "accessToken": "9a0511de65229e046f3dad049d8da5bdd",
    "refreshToken": "555ff975fb1850dc6f96ece3cdfb020bc7695d3f:ce46366f0d67d600493e17b2e8fa6053",
    "instanceUrl": "https://page-dream-9422-dev-ed.cs70.my.salesforce.com",
    "loginUrl": "https://test.salesforce.com/",
    "username": "test-eizjxrgpwekh@example.com",
    "clientId": "PlatformCLI",
    "devHubUsername": "allan.oricil@hpe.com",
    "isDevHub": false
}
````
2 - After that I tried to find the push command and it was still not showing up
3 - Closed and Opened VSCode in the same Workspace and this time the command was appearing. This is probably because the files are read during the Activation of the extension. Maybe you can change it to read those files when they change in the .sfdx with a file listener. This way the user does not need to close and open the project again.

![image](https://user-images.githubusercontent.com/55927613/100341250-3b560f00-2fd4-11eb-87ec-78a3026582ef.png)

## 2nd Test
I also added a random string on the `devHubUsername` prop and the command also appeared. So this devhubusername seems to be just used to show the push command, and it actually can be anything. Does it make sense? Maybe there is another way to control this. 

````json
{
    "orgId": "00D3D0000003PlcUAE",
    "accessToken": "9a0511de65229e046f3dad049d8da5bdd",
    "refreshToken": "555ff975fb1850dc6f96ece3cdfb020bc7695d3f:ce46366f0d67d600493e17b2e8fa6053",
    "instanceUrl": "https://page-dream-9422-dev-ed.cs70.my.salesforce.com",
    "loginUrl": "https://test.salesforce.com/",
    "username": "test-eizjxrgpwekh@example.com",
    "clientId": "PlatformCLI",
    "devHubUsername": "blabla",
    "isDevHub": false
}
````

**Comment by AllanOricil** [comment]
I authorized a new Scratch Org created by my colleague using the VSCode Extension and the same problem happened again. The auth file inside `./sfdx` does not have the devHubUsername again. Here is the Channel output of the command vscode executed:

![image](https://user-images.githubusercontent.com/55927613/100631202-5ea9f280-3323-11eb-8e2a-91933db99be2.png)

![image](https://user-images.githubusercontent.com/55927613/100631306-7aad9400-3323-11eb-8f86-8c3c402aa418.png)

**Comment by AnanyaJha** [comment]
Hi @AllanOricil okay so it looks like the issue here is that the CLI does not reliably add the devhubusername attribute when you log in using a user on the dev hub and the generate password/key for the scratch org. I can log a new bug to look into whether the CLI should be adding in the devhubusername attribute in this scenario or whether there's a different attribute we can use to reliably detect a scratch org. As we discussed earlier, the workaround for now is to manually add in the devhubusername attribute. Thanks for reporting this!

**Comment by AllanOricil** [comment]
> Hi @AllanOricil okay so it looks like the issue here is that the CLI does not reliably add the devhubusername attribute when you log in using a user on the dev hub and the generate password/key for the scratch org. I can log a new bug to look into whether the CLI should be adding in the devhubusername attribute in this scenario or whether there's a different attribute we can use to reliably detect a scratch org. As we discussed earlier, the workaround for now is to manually add in the devhubusername attribute. Thanks for reporting this!

@AnanyaJha Thank you for your response

**Comment by dcstuff** [comment]
This bug should be a top priority only because I hit it today and it's a minor inconvenience!
1. Authorize to an org, use credentials of someone else's scratch org. Rare use case, sure, but it happens!
2. SFDX: Push blah blah command not there

`sfdx force:source:push` works as expected.
