### ISSUE TITLE
Error when upgrading to 51.7.0 for APEX extension

### ISSUE THREAD

**Issue by alexandra7611** [forcedotcom/salesforcedx-vscode#3132]
### Summary

Get error when trying to update the APEX extension

### Steps To Reproduce:

1.  Click Update to 51.7.0 
1.  [2021-04-07 14:30:48.744] [renderer1] [error] extension/package.json not found inside zip.: validating: extension/package.json not found inside zip.
    at G.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:212029)
    at async G.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)

### Expected result

Installed update

### Actual result

Got error listed above: 
[2021-04-07 14:30:48.744] [renderer1] [error] extension/package.json not found inside zip.: validating: extension/package.json not found inside zip.
    at G.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:212029)
    at async G.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:209233)

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/63663895/113923369-16598000-97ae-11eb-87ad-95c5a2c3d219.png)

**VS Code Version**: 1.54.3

**SFDX CLI Version**:  sfdx-cli/7.93.1-762bca056d win32-x64 node-v14.15.4

**OS and version**: Windows 10 , 10.0.18363 Version 18363

**Comment by sfsholden** [comment]
Hi @alexandra7611, thank you for reaching out to us about this issue.

Do you see a different result if you try any of the following?
1. Uninstalling and reinstalling the Apex extension.
2. Installing a different version of the Apex extension.
3. Using a different version of VSCode. For downloading an older version, please see https://code.visualstudio.com/updates.


Thank you,
Shelby

**Comment by alexandra7611** [comment]
@sfsholden 

1. Uninstalling and reinstalling the Apex extension.  - I uninstalled the entire extension pack and tired to reinstall and get this:[2021-04-08 07:20:58.459] [renderer2] [error] ["validating: extension/package.json not found inside zip.","    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)","    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]
[2021-04-08 07:20:58.500] [renderer2] [error] extension/package.json not found inside zip.: validating: extension/package.json not found inside zip.
    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)
    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)

2. Installing a different version of the Apex extension. - I am not sure how to try this as we can not download anything directly to our devices.
3. Using a different version of VSCode. For downloading an older version, please see https://code.visualstudio.com/updates. - now have 1.55.0 of VSCode and still am seeing the error.

Thanks!

**Comment by sfsholden** [comment]
@alexandra7611

1. I'd like to make sure that the other Salesforce extensions have installed correctly, or if this is specific just to the Apex extension. Would it be possible to get a screen of the extension pack? Here's an example of what I'm looking for:
![salesforce-extension-pack-view](https://user-images.githubusercontent.com/45604118/114053084-da74f800-984b-11eb-9fe0-895ba0724305.png)

2. Here's some additional information for installing an older version of an extension. When an extension is installed, there will be a gear icon that lets you configure more about your extension.
![installing-different-extension-version](https://user-images.githubusercontent.com/45604118/114052113-f9bf5580-984a-11eb-9793-d1596b467f29.png)
Additional Resource - https://code.visualstudio.com/docs/editor/extension-gallery#_manage-extensions

3. Does the issue still occur for older versions of VSCode? I do not believe this to be the root cause, but I would like to make sure. This would likely be a good candidate to check against: https://code.visualstudio.com/updates/v1_52


Thank you again for all the info!

**Comment by alexandra7611** [comment]
@sfsholden  
1. No when this fails to install it reverts the install all the other extension items:
![image](https://user-images.githubusercontent.com/63663895/114054092-28422e00-9855-11eb-824c-8be7af2f4ce7.png)

2. I can not install the extension so I do not have an option to install another version.
3. Like I mentioned we are not able to download anything directly onto our device and it seems to upgrade automatically so I am not sure how to test this.
Thanks!

**Comment by sfsholden** [comment]
@alexandra7611 What happens if you click the Install link on the individual extensions? Same result for all of them?

**Comment by alexandra7611** [comment]
@sfsholden 
When trying to install the Apex Interactive Debugger, Apex Replay Debugger or Apex I get the same errors, the rest of the installs work:
[2021-04-08 11:07:04.933] [renderer1] [error] ["validating: extension/package.json not found inside zip.","    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)","    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]
[2021-04-08 11:07:04.965] [renderer1] [error] extension/package.json not found inside zip.: validating: extension/package.json not found inside zip.
    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)
    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)
[2021-04-08 11:07:08.067] [renderer1] [error] ["validating: extension/package.json not found inside zip.","    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)","    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]
[2021-04-08 11:07:08.068] [renderer1] [error] extension/package.json not found inside zip.: validating: extension/package.json not found inside zip.
    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)
    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)
[2021-04-08 11:07:11.006] [renderer1] [error] ["validating: extension/package.json not found inside zip.","    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)","    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]
[2021-04-08 11:07:11.028] [renderer1] [error] extension/package.json not found inside zip.: validating: extension/package.json not found inside zip.
    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)
    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)

![image](https://user-images.githubusercontent.com/63663895/114060140-af45d500-985a-11eb-8c0c-6996826947c4.png)

Thanks!

**Comment by sfsholden** [comment]
@alexandra7611 That does definitely confirm the issue is with the Apex extension then. 

We just released version 51.8.0. Do you have the same issue when upgrading to this version?

Also could you please confirm for me - were you using the Apex extension prior to 51.7.0?

Thanks!

**Comment by alexandra7611** [comment]
@sfsholden
I just tried the new version and get the same error I think:
[2021-04-08 14:15:38.001] [renderer1] [error] ["validating: extension/package.json not found inside zip.","    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)","    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]
[2021-04-08 14:15:38.019] [renderer1] [error] extension/package.json not found inside zip.: validating: extension/package.json not found inside zip.
    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)
    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)


I was using it prior to this I think it was v.51.2.0

Thanks!

**Comment by sfsholden** [comment]
@alexandra7611 This may be similar to #2967 as this appears to be a problem at the VSCode level. Usually the resolution is to delete the extensions and redownload them.

Since you have already tried doing this, I think it would be worth doing some additional clean up first.

The extensions download into a `.vscode` folder (see below resource for the full folder path). Please remove any salesforce.salesforcedx-* extensions that you find in this folder.
More info: https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions

After these old extensions are cleaned up, please try to redownload them and let us know if this unblocks you.

Thank you again for all your patience!

**Comment by alexandra7611** [comment]
@sfsholden 
I have tried this and sadly I am still getting an error. 

At least 3 others at my company are having the same issue as well.

Thanks!

**Comment by sfsholden** [comment]
@alexandra7611 Please open an issue directly to VSCode - https://github.com/microsoft/vscode/issues. This issue is happening from within VSCode itself - not the extension. 

Thank you again for all the information - I'm sorry we weren't able to unblock you from our end.

**Comment by alexandra7611** [comment]
@sfsholden Has there been any other issues with this install? VSCode thought it was maybe my local firewall but that does not seem to be the case.

**Comment by sfsholden** [comment]
@alexandra7611 Sorry to hear the issue hasn't been resolved yet. There have not been any other reports of installation issues with the extensions.

We released v51.10.0 of the extensions today. In case it helps, here was the process I went through to download and install the extension directly from the marketplace. As a side note - I confirmed after unzipping the vsix that the package.json was present for Windows.

**Guide for downloading and installing a vsix directly**: 
https://code.visualstudio.com/docs/editor/extension-gallery#_can-i-download-an-extension-directly-from-the-marketplace

**Marketplace Link for Downloading the Salesforce Extension Pack**:
https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode

**Vsix Unzipped with package.json**:
![vsix_download](https://user-images.githubusercontent.com/45604118/115791459-a6d6b980-a385-11eb-8ebd-595b627f2de5.png)

**Comment by alexandra7611** [comment]
@sfsholden  It looks like the manual route is the only route that works right now, it seems like there is a certain order that they need to be installed in. Can you please tell me the correct order to install the 8 items in the Salesforce Extensions Pack in?

Thanks!
