### ISSUE TITLE
SFDX:retrieve taking a too long time

### ISSUE THREAD

**Issue by shan0076** [forcedotcom/salesforcedx-vscode#4662]
I am using the SFDX:Retrieve function of Visual Studio Code (I am not running any command for retrieve), but it is just loading the icon , but not showing any error/any success as well. I am facing this issue since my OS got Updated.

<img width="1512" alt="Screenshot 2023-02-03 at 5 33 58 pm" src="https://user-images.githubusercontent.com/124129845/216570956-15bc1066-a3f0-4208-a851-5c0b3a8884e3.png">

OS Information
**Chip - Apple M1 Pro**
**MacOs Ventura - Version 13.2**

**Comment by gbwibawa** [comment]
I'm experiencing this issue as well. The command `SFDX Retrieve from Org` runs indefinitely while this message is shown on the screen.
<img width="463" alt="image" src="https://user-images.githubusercontent.com/50224814/217387917-4eaae948-37b2-4a45-9268-6c476fc37484.png">

Updated cli to the latest version 7.186.2 but it didn't help.

**Comment by svittalahhs** [comment]
I had the same issue with the version 57.3.0. The retrieve was not going through for an org in cs133. Switched back to 56.14.0 and it worked.

**Comment by shan0076** [comment]
How can I switch back to the 56.14.0 ?

**Comment by svittalahhs** [comment]
in vscode -> salesforce extention pack -> Under Uninstall there is an option to install a previous version. @shan0076

**Comment by shan0076** [comment]
@svittalahhs  I have tried this but not working for me

**Comment by satishpersonal** [comment]
I also have the same issue it really takes long time to retrieve the metadata and sometimes says the "The ORG Cannot be Found"

**Comment by pedrohenriquefelima** [comment]
I am also experiencing the same issue. I tried recreating a new project folder but it didn't resolve the issue. I also tried downgrading my version as suggested by @svittalahhs . If I find a fix, I will be back.

**Comment by QualRay** [comment]
> @svittalahhs I have tried this but not working for me



> in vscode -> salesforce extention pack -> Under Uninstall there is an option to install a previous version. @shan0076

Thank you!
Along with this, I deleted the package.xml and created a new one and finally it worked.

**Comment by rileySFDEV** [comment]
Getting same issue on 2.22.7

**Comment by achere** [comment]
I'm also experiencing this issue 2.22.7 using `sf project retrieve start`

Are we sure that's a CLI problem and not org latency?

**Comment by rileySFDEV** [comment]
> I'm also experiencing this issue 2.22.7 using `sf project retrieve start`
> 
> Are we sure that's a CLI problem and not org latency?

Deleted .sf and .sfdx and Developer: Reload Window then ran SFDX: Log out of all authorised orgs fixed it 
@achere

**Comment by diyer** [comment]
@etaussig @samwolfe-stripe @achere @pedrohenriquefelima @rileySFDEV @shan0076 
Aer you seeing issues with slow deploy or retrieve? We have created a new issue to gather some data for diagnosis and analyze if this is a server side issue or not https://github.com/forcedotcom/salesforcedx-vscode/issues/5496
Can you please provide the required information on that issue thread?
cc: @peternhale

**Comment by achere** [comment]
@diyer in my case, it was a server instance issue that was resolved by the support

**Comment by diyer** [comment]
Thank you @achere Do you happen to have any investigation link for the server issue?

**Comment by etaussig** [comment]
I’m not experiencing the issue anymore.

**Comment by achere** [comment]
@diyer Salesforce Support Case #45990537

**Comment by AhaTheGhost** [comment]
I concur with this issue. After updating to version 61.12.0 six days ago, I experienced significantly longer retrieval times, taking minimum 10 minutes. This issue persisted until I reverted to version 62.11.0, which resolved the problem and now it is taking between 40 seconds to two minutes. It seems like something in the latest update is affecting the performance of the SFDX: Retrieve function.

VS Code Insider version: 1.93.0-insider (user setup)
OS: Windows 11 Pro, x64 10.0.22631

**Comment by diyer** [comment]
@AhaTheGhost we have not made updated related to deploy/retrieve functionality in our latest extensions version. I think it could be a one off thing on your end. Please try the lates version and let us know if the delay is indeed related the extension version. Ty!

**Comment by diyer** [comment]
Closing this issue, please open a new one for any new issues with proper repro steps. ty!

**Comment by laissaouibrahim** [comment]
the issue still persisting in 2026. 
I put a workaround here : https://github.com/forcedotcom/cli/issues/3306#issuecomment-3703658387
