### ISSUE TITLE
Getting "Metadata API request failed: Cannot read properties of null (reading 'split') " When Trying to Deploy

### ISSUE THREAD

**Issue by dornaldski2** [forcedotcom/salesforcedx-vscode#4873]
### Summary

Duplicate of 4871 but I think 4871 was closed whilst still impacting users.

I updated my sfdx-project.json from v53.0 to v57.0.  VS Code installed updated extensions.  Now when I try to deploy a file I get the message "Metadata API request failed: Cannot read properties of null (reading 'split')" when trying to deploy.

Works for some orgs but not others.  Not related to preview/non-preview as both I have tested are non-preview but works in one and not the other.

### Steps To Reproduce:

1.  Right click and deploy a file to an org.  

### Expected result

File should be deployed to Org.

### Actual result

Metadata API request failed: Cannot read properties of null (reading 'split').  File is not deployed (in this case a screen flow but is same for classes)

### Additional information

**Salesforce Extension Version in VS Code**: v 57.14.1

**SFDX CLI Version**:
7.201.6

**OS and version**:
Win 10 Enterprise
OS Build 19044.2965

**Comment by stevemarinelli** [comment]
@randi274 looks like @dornaldski2 beat me to the punch with creating a new issue related to our discussion on #4863, so I'll add my findings here.

I was able to successfully retrieve the metadata using the CLI directly:, 
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/34689228/467bccb1-0193-4246-bbfa-b0ec8ac0087d)

However I cannot retrieve using the VS Code extension:
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/34689228/16d65359-1fd1-4a3e-a90b-9aff2ee37310)

Interestingly enough, I was able to retrieve successfully using the VS Code extension in the same SFDX project for a different sandbox org, which is also on v58.

**Comment by randi274** [comment]
@dornaldski2 I encountered this issue this morning as well, went on to work on other items, and then when I reopened the project it had disappeared! Have you found this to be the case as well?

For others that may join us - does reauthorizing the org & rebooting VS Code resolve the issue? Also, is anyone working against a non-source tracked org (like a dev org), or is everyone working with source-tracked sandboxes or scratch orgs?

**Comment by takumaCeo** [comment]
I tried re-authing the org, reinstalling vscode extensions, reinstalling the cli, rebooting, none of them resolved the issue for me. All my orgs are source tracked,

**Comment by JayverLance** [comment]
Am getting this error as well, anyone figured out what is causing this?

**Comment by mmhasanovee** [comment]
Facing the same issue, this needs to be fixed. I did a clean install of everything, still, the issue persists. I think it's related to sfdx version.
 Facing the issue in both Mac, and Windows.

**Comment by Pherresa** [comment]
I'm also getting this error since I updated sfdx to 7.201.6-4edd82d.

I am working with a source tracked org, and reauthorizing the org and rebooting VS doesn't work. 

Thanks!

**Comment by JayverLance** [comment]
I've just resolved this issue on my VS Code by reverting Salesforce Extension Pack to v57.10.2.  I've also installed the older versions of Apex, Aura Components, Apex Replay Debugger, Salesforce CLI Integration, Apex Interactive Debugger, Lightning Web Components, SOQL, and Visualforce to the versions from 1 month ago.  I only started having this issue last week when my VS Code automatically updated the Extensions to an update 1 week ago.

**Comment by dornaldski2** [comment]
A temporary fix for the issue is to regress the version of Salesforce CLI extension to the earliest v57.

Unsure which version introduced the error so the science behind selecting 57.2.1 is not exact but it works for us.

Clearly this is a workaround, not a solution to the issue, therefore I expect this bug to remain in place. But nice to know it's definitely an issue with the CLI extension.

**Comment by dornaldski2** [comment]
Should have read JayverLance's comment above first.

Good to see its the same resolution with a bit more consideration to getting the latest working version.

**Comment by randi274** [comment]
@JayverLance you had mentioned on the other issue you were able to get this error when deleting source tracking files. Are you able to reproduce the error consistently by deleting specific files, or an entire directory?

**Comment by JayverLance** [comment]
@randi274 ,  just to clarify what I meant was that I encountered this issue and the other issue simultaneously which made me conclude that they could be related.  I think it was someone else who mentioned that they consistently encountered the issue when deleting the tracking files under .sf/org/

**Comment by JayverLance** [comment]
Anyone heard any update on this issue?  Is it safe to install the latest version of the Salesforce Extension Pack and/or the Salesforce CLI Integration?  @randi274 any update from your end?

**Comment by randi274** [comment]
Thanks @JayverLance you were spot on with your diagnosis! We were able to reproduce the issue today when working on an initial fix for the slow deployments issue.

For me to reproduce:
- Work with a source tracked org
- Run the CLI command `sfdx force:source:tracking:clear`
- Try to deploy again with that source tracked org
- Metadata deploy error

To work around this, I had to delete the entire `.sf` directory, and then source tracking worked as expected. The issue is coming from a shared dependency that the extensions and the CLI both use, so one of our teams will need to take a look to address that.

**Comment by renz-dev** [comment]
Currently having this problem on v58.0.1 so I downgraded to 57.10.2 for now

**Comment by gatekepa** [comment]
> Thanks @JayverLance you were spot on with your diagnosis! We were able to reproduce the issue today when working on an initial fix for the slow deployments issue.
> 
> For me to reproduce:
> 
> * Work with a source tracked org
> * Run the CLI command `sfdx force:source:tracking:clear`
> * Try to deploy again with that source tracked org
> * Metadata deploy error
> 
> To work around this, I had to delete the entire `.sf` directory, and then source tracking worked as expected. The issue is coming from a shared dependency that the extensions and the CLI both use, so one of our teams will need to take a look to address that.

I tried the above workaround, deleting the entire .sf directory, however this didn't help.

Reverting back to 57.10.2 did help.

**Comment by mikearthur7b0** [comment]
I'm getting this with v58.1.1, reverting to v57.10.2 did not help, but in both cases 'Deployment Status' in sandbox shows successful deployment.
For a few weeks now, the message 'Running SFDX: Deploy Source to Org' stays for a long time, but 'Deployment Status' shows that the deploy completed quickly.

**Comment by jeffb-sfdc** [comment]
@pibenett , I've tried to reproduce the issue, but even setting `sourceApiVersion` to "57.0" (in sfdx-project.config), and running `sfdx force:source:tracking:clear`, I have not been able to reproduce the issue.  Here's my configuration:

Salesforce extension: v58.2.0
sfdx: v7.205.6
Running on Mac OSX
Using a source tracked org (a developer edition org, with source tracking enabled)

steps:
1. In sfdx-project.json I set the source API version to 57.0
2. then ran `sfdx force:source:tracking:clear`
3. opened an Apex ".cls" file
4. modified the file
5. right-clicked in the file
6. after the contextual menu opened, I selected "SFDX: Deploy This Source to Org"

...it then deploys, and I don't get any errors.

To those on this thread and are having an issue with deploying:
1. There has been some recent work in the area that looks at the API version.  If you update the SF extension to v58.2.0, and update sfdx to its latest version, does the problem still exist?
2. If you still experience the issue, I know there's an error of "Metadata API request failed: Cannot read properties of null (reading 'split')" being reported, but is there any other info, like a stack trace, source file name, and/or line number?
3. if the answer to `#2` was "no", then please try this:
* Open VSCode's developer tools (select menu Help > Toggle Developer Tools)
* Click on the Console tab
* Right-click, and select "Clear Console"
* Go back to VS Code's window
* Modify your Apex file, right-click, and then select "SFDX: Deploy This Source to Org"

If you get the error, go back to the dev tools window.  Is there any other information that's in the dev tool's Console?

And last, I listed the steps I performed.  If you are still experiencing this issue issue, what steps are you taking?  Are they any different from what I'm doing?

**Comment by jeffb-sfdc** [comment]
Yea, there was a fix that went in with v58.2.0 that fixed some issues with the sourceApiVersion, and it effected metadata files and deploy & retrieve.  It sounds like this has been resolved so I am going to close this issue.

**Comment by jeffb-sfdc** [comment]
@takumaCeo I attempted to reproduce the issue, but this is working for me.  From your post, it's a little unclear as to where the error is happening (in the Extension, or in sfdx).  Here is what I did:

A) While in VS Code and using our extension...
* Modified two of the Apex classes within `force-app/main/default/classes`
* Select the `classes` folder
* Right-click on `classes` folder
* Select `SFDX: Deploy Source to Org`


B) Using sfdx...
* in a terminal, ran `sfdx project deploy start`

At this point, I think the original issue that was reported in this ticket has been fixed.  If you still experience the issue you reported, please do the following:
1. open a new ticket
2. try to narrow down the issue, as this will help us investigate and fix the issue
3. report errors you see in Visual Studio Code's Terminal and Output panels.
4. Open Visual Studio Code's developer tools (menus Help > Toggle Developer Tools)
5. Switch to the developer tool's Console tab
6. Clear the console
7. Reproduce the error, and report back in the new ticket any errors that were reported.

Also, if you are experiencing the error while running sfdx, then that most likely is a bug in sfdx, and should be reported in their repo.

**Comment by manojpgoswamigit** [comment]
downgrading the extension to v57.7.0 worked like a charm.

**Comment by valon-loshaj** [comment]
FYI - This is still an issue...need to revert to 57.10.2 and bingo-bango...works like a charm.

Can someone from Salesforce fix this?
