### ISSUE TITLE
The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted for version Version: 1.93.1

### ISSUE THREAD

**Issue by jean-feng** [forcedotcom/salesforcedx-vscode#5869]
### Summary

The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### Steps To Reproduce:

I got a new C driver, installed new Windows:
Edition Windows 10 Enterprise
Version 22H2
Installed on ‎9/‎6/‎2024
OS build 19045.4894
Experience Windows Feature Experience Pack 1000.19060.1000.0

Then I installed sf @salesforce/cli/2.58.7 win32-x64 node-v20.17.0

Java JDK-21

Visual Studio Code
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

Once I installed Salesforce Extension Pack
v61.12.0

I got The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### Expected result

_Describe what should have happened_.

### Actual result

c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info  - 10:54:56 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info  - 10:55:10 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info  - 10:55:21 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Info  - 10:55:33 AM] Connection to server got closed. Server will restart.
c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Unexpected close tag
Line: 1886
Column: 15
Char: >
    at error (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:684:7)
    at closeTag (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:878:9)
    at SAXParser.write (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\sax\lib\sax.js:1460:13)
    at exports.Parser.Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\yfeng\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-61.12.0\node_modules\xml2js\lib\parser.js:5:59)

Node.js v20.15.1
[Error - 10:55:45 AM] Connection to server got closed. Server will not be restarted.

### Additional information

_Feel free to attach a screenshot_.

**Salesforce Extension Version in VS Code**:

**Salesforce CLI Version**:

**OS and version**:

**VS Code version**:

**Most recent version of the extensions where this was working**:

**Comment by peternhale** [comment]
[@jean-feng](https://github.com/jean-feng) tell me about your project, was an existing opened after the upgrades or was it a new project.

Given the error, the LWC language server is trying to parse a xml file. Do you have any xml files in your project with the string "er = new Error(er)" If so, could you share the details of that file here.

Could you also try creating a new project to see if the LWC language server starts properly?

**Comment by jean-feng** [comment]
@peternhale I pull the branch from repository since everything in my C is new and I followed normal instructions for salesforc deployment processes since I already changed PC for couple of times in the past. Only difference is I downloaded the newest version for each step as before.  In the beginning, everything seems good and I did not pay attention to the extension errors. since I can retrieve existing component like Apex code that I modified until I added some metadata in salesforce. When I tried to download those custom metadata, I got  "Missing fullName on CustomLabel in \force-app\main\default\labels\CustomLabels.labels-meta.xml" even that is not label at all. And then I went to existing customLabel, and I tried to retrieve it, and then I saw "LWC language server error". Then I uninstalled Salesforce Extension Pack, removed all the extension, and installed it again, then I noticed "LWC language server error". I still can pull existing ApexClass or custom metadata, however, when I tried to retrieve ApexPage, and then I got this "LWC language server error" too without retrieving.  This is just wired. The Org Browser for downloading any existing stuff, first pop up "Are you sure you want to overwrite error.." Once you click overwrite button, I got Missing fullName on CustomLabel in \force-app\main\default\labels\CustomLabels.labels-meta.xml".  Nothing is changed in fullsb or prod, If I tried to download anything, I got the same error also. I just think something wrong with VSCode. Actually, I redo everything in one drive again, The same thing still happened.  My C driver is new including window operation system since Dell replaced my C drive. The project is pull current branch.

**Comment by jean-feng** [comment]
@peternhale I think I resolved the issue. Someone checked in customLabel with extra starting tag, once I fixed that, I dont see LWS Language Server crashed error and I am able to download and retrieve without problem. Sorry for the confusion.

**Comment by peternhale** [comment]
@jean-feng thanks for letting us know, however, the language server should not crash like this for a malformed file. Would you be willing to share the breaking change so I might file a bug, so we can have a look at the root cause and fix it if possible?

**Comment by jean-feng** [comment]
I can reproduce it:

  1.  I added a starting tag in customLabel xml file without an ending tag.
  2.  Save it
  3.  Go to any extensions,  either install or uninstall, you will see that error I showed you before.
  4.  I think if you tried to retrieve some xml, I got that error too.

Only thing I fixed in my project is customLabel xml file, and then all is working. I already check
In work items so far and all is still good.

**Comment by peternhale** [comment]
@jean-feng thank for the reproduction steps. I was able to cause the error. I am logging a bug.

**Comment by aniruddhanath1** [comment]
Hi Team,

This issue still persists. I'm using the following versions:

<img width="351" height="236" alt="Image" src="https://github.com/user-attachments/assets/f069c0a5-8953-462a-9392-9d39a5cf0df4" />

Version: 1.102.2 (system setup)
Commit: c306e94f98122556ca081f527b466015e1bc37b0
Date: 2025-07-22T12:15:48.520Z
Electron: 35.6.0
ElectronBuildId: 11847422
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.26100

It gives me the following error once I start my VSCode - 

[Info  - 3:48:22 PM] Connection to server got closed. Server will restart.
true
c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\sax\lib\sax.js:658
    er = new Error(er)
         ^

Error: Invalid character in entity name
Line: 28
Column: 68
Char: =
    at error (c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\sax\lib\sax.js:658:10)
    at strictFail (c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\sax\lib\sax.js:684:7)
    at SAXParser.write (c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\sax\lib\sax.js:1522:13)
    at exports.Parser.Parser.parseString (c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\xml2js\lib\parser.js:5:59)
    at c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\xml2js\lib\parser.js:338:24
    at new Promise (<anonymous>)
    at exports.Parser.Parser.parseStringPromise (c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\xml2js\lib\parser.js:336:14)
    at Parser.parseStringPromise (c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\xml2js\lib\parser.js:5:59)
    at Typing.declarationsFromCustomLabels (c:\Users\ANIRUDDHA\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-64.5.1\node_modules\@salesforce\lwc-language-server\lib\typing.js:68:47)

Node.js v22.15.1
[Error - 3:48:50 PM] Server process exited with code 1.
[Error - 3:48:50 PM] The LWC Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

Do I need to update any versions of Node.js or Salesforce CLI? Could you please help me resolve this issue?

**Comment by aniruddhanath1** [comment]
Hi @daphne-sfdc - It happens for me in every SFDX project.

**Comment by aniruddhanath1** [comment]
Here is the list of extensions:

<img width="1567" height="649" alt="Image" src="https://github.com/user-attachments/assets/8e8ffd04-d8f6-4c55-a4cf-ab6ea9ba6807" />

<img width="1571" height="415" alt="Image" src="https://github.com/user-attachments/assets/78cd37ec-f5ad-4a60-b056-0d6d008ebc60" />

**Comment by daphne-sfdc** [comment]
I wonder if the issue is caused by something in your code, like the one that @jean-feng originally posted.  Given that it happens in this project but not the empty one, it's a possibility.

The error you posted is
```Error: Invalid character in entity name
Line: 28
Column: 68
Char: =
```

Can you please check your code to see if there are any unexpected uses of the `=` sign?  It seems to me like this might be caused by a variable containing an equal sign in the middle.

**Comment by aniruddhanath1** [comment]
@daphne-sfdc - When I corrected the lines in the CustomLabels.labels-meta.xml and added the jest.config.js file to the project, there are no more LWC server crashing issues.

<img width="605" height="48" alt="Image" src="https://github.com/user-attachments/assets/1653df5e-fcad-478d-9f03-29630bc1dcdc" />

In the above line, the &amp; was like &, before the id query parameter. So, we replaced the & with the &amp;.

<img width="484" height="177" alt="Image" src="https://github.com/user-attachments/assets/e41f744f-5af2-4000-a9f2-48ab469569c9" />

Repeated the same steps here, too.
